modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/rathmerdominik/mmnm-role-assigner/issues/"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/rathmerdominik/mmnm-role-assigner/main/updates.json"
	displayURL="https://github.com/rathmerdominik/mmnm-role-assigner"
	logoFile="mmnmroleassign.png"
	credits="DerHammerclock"
	authors="${mod_authors}"
	description='''${mod_description}'''

[[dependencies.${mod_id}]]
	modId = "mineminenomi"
	mandatory = true
	versionRange = "[0.10.3,)"
	ordering = "AFTER"
	side = "SERVER"

[[dependencies.${mod_id}]]
	modId = "dcintegration"
	mandatory = true
	versionRange = "[3.0.5,)"
	ordering = "AFTER"
	side = "SERVER"
